name: Release
run-name: ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

permissions:
  contents: write

env:
  BIN_NAME: rust-cli-boilerplate

jobs:
  checks:
    name: Check version
    runs-on: ubuntu-latest
    outputs:
      APP_NAME: ${{ steps.info.outputs.app_name }}
      APP_VERSION: ${{ steps.info.outputs.app_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get app info
        id: info
        uses: ./.github/actions/get-info

      - name: Match version check
        uses: ./.github/actions/match-version-check
        with:
          app_version: ${{ steps.info.outputs.app_version }}
          compare_to: ${{ github.ref }}

  make_matrix:
    runs-on: ubuntu-latest
    needs: checks
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      MATRIX_FILE: matrix.jsonc
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - id: set-matrix
        name: Set matrix
        run: |
          echo "matrix=$(grep -v '//' $MATRIX_FILE | jq -c '.')" >> "$GITHUB_OUTPUT"

  build_release:
    name: Build release
    needs: [ checks, make_matrix ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJson(needs.make_matrix.outputs.matrix)}}
      max-parallel: 5
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup just runner
        uses: extractions/setup-just@v2

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        if: ${{ matrix.builder == 'cargo' }}
        with:
          target: ${{ matrix.target }}

      - name: Install cross toolchain
        if: ${{ matrix.builder == 'cross' }}
        run: cargo install cross

      - name: Build for release using ${{ matrix.builder }}
        run: ${{ matrix.builder }} build --target ${{ matrix.target }} --release

      - name: Compress and archive
        id: archive
        uses: ./.github/actions/compress-and-archive
        with:
          filenamebase: ${{ needs.checks.outputs.APP_NAME }}-${{ needs.checks.outputs.APP_VERSION }}-${{ matrix.target }}
          files: LICENSE* README.md CHANGELOG.md
          binary_path: target/${{ matrix.target }}/release/${{ env.BIN_NAME }}${{ runner.os == 'Windows' && '.exe' || '' }}

      - name: Upload artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.archive.outputs.archive_name }}
          path: ${{ steps.archive.outputs.archive_path }}
          if-no-files-found: error
          retention-days: 1
          compression-level: 0  # no compression

      - name: Upload artifact checksum
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.archive.outputs.sha256_name }}
          path: ${{ steps.archive.outputs.sha256_path }}
          if-no-files-found: error
          retention-days: 1
          compression-level: 0  # no compression

  make_release:
    name: Release
    runs-on: ubuntu-latest
    needs: build_release
    # Only run this job if the push event is a tag push
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            Release notes for `${{ github.ref_name }}` are available here: https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md
          files: artifacts/**/*
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref, 'pre') || contains(github.ref, 'beta') || contains(github.ref, 'rc') || contains(github.ref, 'alpha') || contains(github.ref, 'nightly') }}
          # Note: drafts and prereleases cannot be set as latest.
          make_latest: ${{ !contains(github.ref, 'pre') && !contains(github.ref, 'beta') && !contains(github.ref, 'rc') && !contains(github.ref, 'alpha') && !contains(github.ref, 'nightly') }}
          fail_on_unmatched_files: true
          # no need to specify GITHUB_TOKEN here, it is automatically provided by GitHub Actions

  publish:
    name: Publish crate
    runs-on: ubuntu-latest
    needs: make_release
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          # specify stable to match crates.io requirements
          # and avoid installing all the toolchains in rust-toolchain.toml
          toolchain: stable
      - name: Publish crate
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: true
